name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest # Or specify a pnpm version if needed

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Build project
        run: pnpm build
        env:
          # Add any required environment variables for the build process here
          # Example: DATABASE_URL needed for 'prisma generate'
          # DATABASE_URL: ${{ secrets.DATABASE_URL }} # You'll need to add this secret to your GitHub repo settings
          # NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          # ... other variables
          # For now, I'll add a placeholder DATABASE_URL. Replace this in your repo secrets.
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Placeholder